### ISSUE TITLE
Error reading TAR_reads.bed file in calcHMMrefFlat

### ISSUE THREAD

**Issue by dkeitley** [fw262/TAR-scRNA-seq#3]
Hi,

I'm running into the following error when running the pipeline on my single-cell dataset: 

```
rule calcHMMrefFlat:
    input: TAR_reads.bed.gz
    output: TAR_reads.bed.gz.noDir.refFlat.refFlat, TAR_reads.bed.gz.withDir.refFlat.refFlat
    jobid: 0

Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: read.delim -> read.table
```

The TAR_reads.bed.gz file is empty which suggests that the problem lies in the calcHMMbed step.  

I've set the following parameters in the config.yaml file which, except expectedCells, should be the same as the default. 

```
GLOBAL:
    allowed_mismatch: 10 # outFilterMismatchNmax parameter for STAR alignment
    BC_range: # barcode range
        first: 1
        last: 16
    UMI_range: # unique molecular identifier range
        first: 17
        last: 28 # 28 for v3, up to 26 for v2

expectedCells: 25000
MERGEBP: 500
THRESH: 10000000
```

Any suggestions as to what might be causing the error?

Many thanks,

Dan
